# Generated by Django 4.2.1 on 2023-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACIST', 'Pharmacist'), ('ASSISTANT', 'Assistant')], default='Assistant', max_length=20),
        ),
    ]
