# Generated by Django 4.2.1 on 2023-06-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dash', '0002_alter_branch_location_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_detail', models.TextField(max_length=255)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='calendar_module.appointment')),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
            ],
        ),
    ]
