# Generated by Django 4.2.1 on 2023-06-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='appointment',
        ),
    ]
