# Generated by Django 4.2.1 on 2023-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0002_remove_calendar_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
