# Generated by Django 4.2.1 on 2023-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0003_delete_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime_start',
            field=models.DateTimeField(null=True),
        ),
    ]
