# Generated by Django 4.2.1 on 2023-06-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0006_sale_alter_supplier_supplier_email_sale_detail'),
        ('calendar_module', '0004_appointment_datetime_end_appointment_datetime_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assist_dash.order_stock'),
        ),
    ]
