# Generated by Django 4.2.1 on 2023-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0005_appointment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
