# Generated by Django 4.2.1 on 2023-07-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0006_remove_appointment_datetime_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_end',
        ),
    ]
