# Generated by Django 4.2.1 on 2023-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_prefix', models.CharField(default='B', editable=False, max_length=2)),
                ('Branch_Name', models.CharField(max_length=50)),
                ('Branch_address', models.CharField(max_length=255)),
                ('Branch_state', models.CharField(choices=[('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Malacca', 'Malacca'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Penang', 'Penang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Selangor', 'Selangor'), ('Terengganu', 'Terengganu'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Labuan', 'Labuan'), ('Putrajaya', 'Putrajaya'), ('default', 'default')], default='default', max_length=20)),
            ],
        ),
    ]
