# Generated by Django 4.2.1 on 2023-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_location',
            name='Branch_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branch_location',
            name='Branch_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
