# Generated by Django 4.2.1 on 2023-06-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Supplier_Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
