# Generated by Django 4.2.1 on 2023-06-05 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0003_alter_supplier_supplier_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='Supplier_Rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
