# Generated by Django 4.2.1 on 2023-06-05 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0002_alter_branch_location_branch_name_and_more'),
        ('assist_dash', '0004_alter_supplier_supplier_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(choices=[('Supplement', 'Supplement'), ('Medication', 'Medication'), ('default', 'default')], default='default', max_length=50)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Expirydate', models.DateField(null=True)),
                ('Product_Barcode', models.TextField(max_length=16)),
                ('Product_Price', models.DecimalField(decimal_places=2, default=1, max_digits=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('Product_Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('Unit_Dose', models.TextField(max_length=50)),
                ('Brand', models.CharField(choices=[('default', 'default')], default='default', max_length=50)),
                ('Form', models.CharField(choices=[('Tablet', 'Tablet'), ('Liquid', 'Liquid'), ('default', 'default')], default='default', max_length=50)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('Order_Name', models.TextField(max_length=50)),
                ('Order_Total', models.DecimalField(decimal_places=2, default=1, max_digits=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('Order_Date', models.DateField(null=True)),
                ('Order_Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=50)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
                ('supplier', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assist_dash.supplier')),
            ],
        ),
    ]
