# Generated by Django 4.2.1 on 2023-06-14 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0003_remove_branch_location_branch_prefix_and_more'),
        ('assist_dash', '0005_product_order_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_total', models.DecimalField(decimal_places=2, default=1, max_digits=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('Sale_Date', models.DateField(null=True)),
                ('Sale_Method', models.CharField(choices=[('e-Wallet', 'e-Wallet'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash'), ('default', 'default')], default='default', max_length=50)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Supplier_Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name='Sale_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Quantity', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
                ('product', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assist_dash.product')),
                ('sale', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assist_dash.sale')),
            ],
        ),
    ]
