# Generated by Django 4.2.1 on 2023-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0006_sale_alter_supplier_supplier_email_sale_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Barcode',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='Unit_Dose',
            field=models.CharField(max_length=50),
        ),
    ]
