# Generated by Django 4.2.1 on 2023-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0007_alter_product_brand_alter_product_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.CharField(choices=[('Supplement', 'Supplement'), ('Medication', 'Medication')], default='Medication', max_length=50),
        ),
    ]
