# Generated by Django 4.2.1 on 2023-06-25 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0008_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_stock',
            name='Order_Quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
