# Generated by Django 4.2.1 on 2023-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0009_alter_order_stock_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_stock',
            name='Order_datetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order_stock',
            name='Order_datetime_start',
            field=models.DateTimeField(null=True),
        ),
    ]
