# Generated by Django 4.2.1 on 2023-06-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0010_order_stock_order_datetime_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_stock',
            name='Order_Date',
        ),
    ]
