# Generated by Django 4.2.1 on 2023-06-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0011_remove_order_stock_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_stock',
            old_name='Order_datetime_start',
            new_name='Order_datetime',
        ),
        migrations.RemoveField(
            model_name='order_stock',
            name='Order_datetime_end',
        ),
    ]
