# Generated by Django 4.2.1 on 2023-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0012_rename_order_datetime_start_order_stock_order_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_stock',
            name='Order_datetime',
        ),
        migrations.AddField(
            model_name='order_stock',
            name='Order_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order_stock',
            name='Order_Time',
            field=models.TimeField(null=True),
        ),
    ]
