# Generated by Django 4.2.1 on 2023-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0014_alter_product_form_alter_product_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Syrup', 'Syrup'), ('Lozenge', 'Lozenge'), ('Topical Creams and Ointments', 'Topical Creams and Ointments'), ('Patches', 'Patches'), ('Inhalers and Nasal Sprays', 'Inhalers and Nasal Sprays'), ('Powder', 'Powder'), ('Drops', 'Drops'), ('Injectable', 'Injectable'), ('Effervescent Tablet', 'Effervescent Tablet'), ('-', '-')], default='-', max_length=50),
        ),
    ]
