# Generated by Django 4.2.1 on 2023-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0015_alter_product_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Barcode',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
