# Generated by Django 4.2.1 on 2023-07-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_dash', '0017_alter_sale_detail_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_detail',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='assist_dash.product'),
        ),
    ]
