# Generated by Django 4.2.1 on 2023-06-04 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6000000000000), django.core.validators.MinValueValidator(6000000000)]),
        ),
    ]
