# Generated by Django 4.2.1 on 2023-06-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_dash', '0005_medical_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical_Record',
        ),
    ]
