# Generated by Django 4.2.1 on 2023-06-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_dash', '0006_delete_medical_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examinination_Date', models.DateField(null=True)),
                ('Diagnosis', models.TextField(max_length=400)),
                ('Treatment', models.TextField(max_length=400)),
                ('patient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pharm_dash.patient')),
            ],
        ),
    ]
