# Generated by Django 4.2.1 on 2023-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_dash', '0007_medical_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='Diagnosis',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='Treatment',
            field=models.TextField(max_length=255),
        ),
    ]
