# Generated by Django 4.2.1 on 2023-06-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0002_alter_branch_location_branch_name_and_more'),
        ('pharm_dash', '0008_alter_medical_record_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_record',
            name='branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location'),
        ),
    ]
