# Generated by Django 4.2.1 on 2023-07-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_dash', '0009_medical_record_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='Examinination_Date',
            new_name='Examination_Date',
        ),
    ]
