# Generated by Django 4.2.1 on 2023-06-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dash', '0002_alter_branch_location_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_Type', models.CharField(choices=[('Low Stock', 'Low Stock'), ('Near Expiration', 'Near Expiration'), ('default', 'default')], default='default', max_length=25)),
                ('Notification_Content', models.TextField(max_length=255)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_dash.branch_location')),
            ],
        ),
    ]
